language: php

php:
  - 7.0
  - 5.6

script:
  - composer self-update || true
  - composer validate
  - composer install
  - ./vendor/bin/phpcs --version
  - ./vendor/bin/phpmd --version
  - ./vendor/bin/phpunit --version
  - ./vendor/bin/security-checker --version
  - ./vendor/bin/security-checker security:check composer.lock
