language: php

php:
  - 7.0
  - 5.6

script:
  - composer self-update || true
  - composer validate
  - composer install
  - ./vendor/bin/behat --version
  - ./vendor/bin/codecept --version
  - ./vendor/bin/grumphp --version
  - ./vendor/bin/jsonlint -h
  - ./vendor/bin/paratest --version
  - ./vendor/bin/php-cs-fixer --version
  - ./vendor/bin/parallel-lint -h
  - ./vendor/bin/phpcs --version
  - ./vendor/bin/pdepend --version
  - ./vendor/bin/phpcpd --version
  - ./vendor/bin/phploc --version
  - ./vendor/bin/phpmetrics --version
  - ./vendor/bin/phpmd --version
  - ./vendor/bin/phpunit --version
  - ./vendor/bin/security-checker --version
  - ./vendor/bin/security-checker security:check composer.lock
